apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec: 
  serviceName: "my-db-headless-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql  
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.36
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: "Test123"
          volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
    
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard